#!/bin/sh
# xgrycj03 Jakub Gryc
# 12/3/2023

export POSIXLY_CORRECT=yes
export LC_ALL=C

EDITR=""
FILENAME=""
DIRNAME=""
DATE=$(date +%Y-%m-%d_%H-%M-%S)
groups=""
marg=0
garg=0
barg=0
aarg=0
bdate=""
adate=""
listarg=0
SLOG=0
last_arg=""

## if variable MOLE_RC not defined, exit 
if [ -z "$MOLE_RC" ]; then
    echo "Promenna \$MOLE_RC neni definovana!"
    exit 1
fi

## create molerc file if not defined
if [ ! -f "$MOLE_RC" ]; then
    mkdir -p "$(dirname "$MOLE_RC")"
    touch "$MOLE_RC"
fi

## set editor
if [ -z "$EDITOR" ]; then
    EDITR=$VISUAL
    if [ -z "$EDITR" ]; then
        EDITR='vi'
    fi
else
    EDITR=$EDITOR
fi



print_help() {
    echo "    Usage:
    ---------------------------------------------------------
    mole -h                               | vypise tento help
    mole [-g GROUP] FILE                  | 
    mole [-m] [FILTERS] [DIRECTORY]       |
    mole list [FILTERS] [DIRECTORY]       |
          "
      }
if [ "$1" = "list" ]; then
    listarg=1
    shift
elif [ "$1" = "secret-log" ]; then
    SLOG=1
    shift
fi



while getopts "g:mhb:a:" OPT; do 
    case $OPT in
        g)
            garg=1
            groups=$OPTARG
            echo "Option g is used"
            ;;
        m)
            
            marg=1
            echo "Option m used"
            ;;
        h)
            print_help
            exit 0
            ;;
        b)
            barg=1
            bdate=$OPTARG
            ;;
        a)
            aarg=1
            adate=$OPTARG
            ;;
        ?)
            print_help
            exit 1
            ;;
    esac
done

if [ 1 -ne $SLOG ]; then
    while [ "$#" -gt 1 ]; do
        shift
    done
fi






last_arg="$1"
if [ -d "$last_arg" ] || [ -z "$last_arg" ]; then
    DIRNAME=$(realpath "$last_arg")
elif [ -f "$last_arg" ]; then
    FILENAME=$(realpath "$last_arg")
fi



write_to_molerc() {
    echo "$1,$2,$3" >> "$MOLE_RC"
}

open_file() {
    $EDITR "$1"
}


if [ 1 -ne $marg ] && [ -n "$FILENAME" ]; then
    open_file "$FILENAME"
    write_to_molerc "$FILENAME" "$groups" "$DATE"
fi





#echo "$FILENAME" >> "$MOLE_RC"

